sudo: false

cache:
    apt: true
    directories:
    - "$HOME/.cache/pip"
    - "$HOME/.ccache"
    - "$HOME/.pip-cache"

dist: trusty

language: python

notifications:
    email: false

matrix:
    include:
    - python: '3.6'
      env: TOXENV="flake8"

install:
    - pip install tox

script:
    - tox -vv
